### ISSUE TITLE
Is not a constructor

### ISSUE THREAD

**Issue by momtr** [avdkishore/node-rabbitmq-client#8]
I think this constructor does not work:

```javascript
const BrokerClient = require('node-rabbitmq-client');
const broker = new BrokerClient.default(config);
````

**Comment by kristianpedersen** [comment]
Same with this code:

```javascript
const RabbitMQClient = require('node-rabbitmq-client');
const client = new RabbitMQClient({});
```

Error: `RabbitMQClient is not a constructor`

Node: 14.16.0
"amqplib": "^0.8.0",
"node-rabbitmq-client": "^3.0.0"

**Comment by tarnacious** [comment]
The library doesn't return a constructor, when the library is required it tries to immediately load configuration and connect to a server. Unfortunately this make's the library unsuitable for a lot of applications. 

The library exports the amqp connection object and four functions to work with the connection which you can see here:

https://github.com/avdkishore/node-rabbitmq-client/blob/9c759cb1523709ad3211c6f75607093716760ca0/src/index.js#L227-L233
